# Monday, August 15 - Lila - Museum Summer 2016 High School Internship Program

[Slack](https://pennds.slack.com)

[Omeka Dashboard](http://hsdemo.upenndigitalscholarship.org/omeka/admin)

[Penn Library Home Page](http://www.library.upenn.edu/)

[Esri Story Map Dashboard](http://www.arcgis.com/home/content.html)


### Schedule
*	At 9:30am, meet Laurie Allen, Assistant Director for Digital Scholarship
*	Learn about writing for the web, creating digital content, and how the internet works!
*	Show Laurie your exhibits and discuss ideas for enhancing your exhibit

#### Tasks due by end of day
*	Using the Outline Topic Cards you created, create one Cascade section for each card, with **at least** a header and a media item or text
  * [Click here to access your Esri Story Map Dashboard](http://www.arcgis.com/home/content.html)
  * Click on the name of your exhibit in the Content menu, then click on "View Application", then click on "Edit"
  * [A guide to creating a Cascade Story Map](https://storymaps.arcgis.com/en/app-list/cascade/tutorial/)
  * If you have an Outline Topic Card with an Item that is a **Visualization from KnightLab ( [Juxtapose](https://juxtapose.knightlab.com/), [StoryMap](https://storymap.knightlab.com/), [Timeline](https://timeline.knightlab.com/), or [SoundCite](https://soundcite.knightlab.com/) )**, use the links here (and linked tutorials above) to create that item and make a note on your Outline Topic Card. To add it to your StoryMap, click the button to add a Media item, select the "Link to Content" tab, and paste in the iframe generated by following the instructions for each visualization above
  * If you have an Outline Topic Card with an Item that is a **Video**, find the video online and make a note on your Outline Topic Card of where to find the video. To add it to your StoryMap, click the button to add a Media item, select the "Link to Content" tab, and paste in the embed code for the video
  * If you have an Outline Topic Card with an Item that is an **Image** upload the image you would like to use as an Item in Omeka. After saving the Items:
    * Open the item for viewing on the Admin side
    * Click on file name under the File Metadata menu on the right hand side of the screen
    * Click on the "Original", "Fullsize", or "Thumbnail" (for the size you want) in the "Direct Links" menu on the right hand side of the screen
    * This opens the image. Copy this url from the address bar to embed the image in your StoryMap
* Be prepared to show your exhibit Outline Topic Cards to Patty and discuss possible media ideas
* Using what you learned from Patty, enhance at least one of your exhibit topics with an interesting piece of media

#### Online Databases of Native American Material
* [ArtStor](http://library.artstor.org/library/)
  * [Sample Search](http://library.artstor.org/library/#3|search|6|All20Collections3A20indian20games|Filtered20Search|||type3D3626kw3Dindian20games26geoIds3D26clsIds3D26collTypes3D26id3Dall26bDate3D26eDate3D26dExact3D26prGeoId3D26origKW3D)
* [Indigenous Peoples of North America Database](http://gdc.galegroup.com/gdc/artemis/?u=upenn_main&p=INDP)
  * [Sample Search](http://gdc.galegroup.com/gdc/artemis/NewspapersFullListPage/NewspapersFullListWindow?failOverType=&query=KE+games&prodId=INDP&windowstate=normal&contentModules=&display-query=KE+games&mode=view&displayGroupName=DVI-Newspapers&limiter=&u=upenn_main&currPage=1&displayGroups=&totalSearchResultCount=&source=fullList&p=INDP&action=e&catId=&activityType=BasicSearch&scanId=CSH)
* [National Museum of the American Indian Collections Search](http://www.nmai.si.edu/searchcollections/home.aspx)
  * [Sample Search](http://www.nmai.si.edu/searchcollections/results.aspx?catids=0&objtypeid=Games%2c+Toys%2c+Gambling&src=1-4)
* [Smithsonian Research Information System](http://siris-archives.si.edu/ipac20/ipac.jsp?profile=allimg)
  * [Sample Search](http://siris-archives.si.edu/ipac20/ipac.jsp?session=14702F1079UT4.31410&menu=search&aspect=subtab164&npp=50&ipp=20&spp=20&profile=allimg&ri=&term=indian+games&index=.GI&x=0&y=0&aspect=subtab164&term=&index=.AI&term=&index=.SI)
* [Smithsonian Collections](http://collections.si.edu/search/index.htm)
  * [Sample Search](http://collections.si.edu/search/results.htm?q=Games&fq=place:%22North+America%22)
* [Penn Museum Online Collections](http://www.penn.museum/collections/)
  * [Sample Search](http://www.penn.museum/collections/advanced.php?a_object_name=games&a_object_number=&a_period=&a_place_name=america&a_culture=&a_maker=&a_credit_line=&a_material=&a_area_locus=&submit_multi=Submit+Query)
* [Penn Museum Videos on Internet Archive](https://archive.org/details/UPMAA_films)
  * [Sample Search](https://archive.org/details/UPMAA_films?sort=-downloads&and[]=game)

#### Cat's Cradle Search Results
* [on ArtStor](http://library.artstor.org/library/#3|search|6|All20Collections3A20cat27s20cradle|Filtered20Search|||type3D3626kw3Dcat27s20cradle26geoIds3D26clsIds3D26collTypes3D26id3Dall26bDate3D26eDate3D26dExact3D26prGeoId3D26origKW3D)
* [on Indigenous Peoples of North America Database](http://gdc.galegroup.com/gdc/artemis/searchResults/actionWin?failOverType=ketx&resetBreadCrumb=&query=TX+cat%27s+cradle&prodId=INDP&windowstate=normal&contentModules=&display-query=TX+cat%27s+cradle&mode=view&limiter=&u=upenn_main&commentary=&totalSearchResultCount=12&displayGroups=&p=INDP&action=e&catId=&activityType=BasicSearch&scanId=CSH)
* [in Smithsonian Collections](http://collections.si.edu/search/results.htm?tag.cstype=all&q=cat%27s+cradle&start=0)
* [at the Penn Museum](http://www.penn.museum/collections/search.php?term=cat%27s+cradle&submit_term=Submit+Query)

#### Narrative Ideas
* How was this game played?
* (If the game came from outside of native America) How did this game come to be played by Native Americans?
* Does this game have a basis in a tradition or story? Is it part of some ritual?
* Who is allowed to play this game? When is it allowed to be played?
* Is this game played in different ways, with different equipment, in different tribes?
* If you would like to focus on an object or collection of objects, how was the object made? How was it used? How was it collected? How did it end up where it is today?
* If you would like to focus on some specific archival material, when was the material recorded? Was it on an expedition? Why was someone recording this?
* Compare a native game to a game or sport that you play or enjoy today

#### Visualization Tools and Examples

* [Timeline.js](https://timeline.knightlab.com/)
  * [Haudenosaunee Creation Story Timeline](http://tbpdh.omeka.net/timelines)
  * [Video Tutorial on how to make a Timeline](https://vimeo.com/143407878)
  * [Click here to get started making a Timeline](https://timeline.knightlab.com/#make)
  * To make a Timeline, follow the instructions at the link above. Click on the "Get the Spreadsheet Template" button to open the template and then save it to your own Google Drive by clicking the "Use this template" button. To edit the contents of the timeline, follow the instructions in the link.
* [Storymap.js](https://storymap.knightlab.com/)
  * To create a StoryMap, follow the link above and click on the "Create a StoryMap Now" button. You will need to sign in to Google to begin creating the StoryMap
* [Juxtapose.js](https://juxtapose.knightlab.com/)
  * To create a Juxtapose, upload the two images you would like to use as Items in Omeka. After saving the Items:
    * Open the item for viewing on the Admin side
    * Click on file name under the File Metadata menu on the right hand side of the screen
    * Click on the "Original", "Fullsize", or "Thumbnail" (for the size you want) in the "Direct Links" menu on the right hand side of the screen
    * This opens the image. Copy this url from the address bar to use when creating the Juxtapose
  * After you have uploaded both images, go to [this link](https://juxtapose.knightlab.com/#create-new) and paste the urls for the images in the Left and Right Images url inputs. Be sure to add the proper credit
  * Update the preview to make certain it looks correct
  * Click the publish button, then copy the iframe it generates to your Google Doc to save for embedding in your exhibit
* [Soundcite.js](https://soundcite.knightlab.com/)
* To create a SoundCite, upload the original audio file you would like to use as an Item in Omeka. After saving the Item:
    * Open the item for viewing on the Admin side
    * Click on file name under the File Metadata menu on the right hand side of the screen
    * Click on the item in the "Direct Links" menu on the right hand side of the screen
    * This opens the audio file. Copy this url from the address bar to use when creating the SoundCite
  * [Follow these instructions to create your clip](https://soundcite.knightlab.com/#create-new)
* [Story Map by Esri](https://storymaps.arcgis.com/en/)
  * [Trilobite Palaeomap](http://esribelux.maps.arcgis.com/apps/MapJournal/index.html?appid=621ca59bf5444d3d8d444638e61c1d1f)
  * [Coastal Monitoring Map](http://storymap.systemsecology.org/)
  * [Appalachia Historical Map](http://marshalluniv.maps.arcgis.com/apps/MapJournal/index.html?appid=bc38294006b242608fdbc65682ae74d4)

#### General Advice for Both of You
  * If you need to scan an image, use the Z Scan in the library (don't forget to change the Settings to "Color" and 600dpi to get the best image)
  * Shannon has a flash drive you can use for the Z Scan, please return it to her at the end of the day
  * If you are having trouble finding content, look at the sample searches above

## People
![alt text](https://avatars2.githubusercontent.com/u/1661248?v=3&s=96 "Sasha Renninger")

Sasha Renninger, Digital Humanities Specialist

215-898-9331 | @sashafr

[sashafr@upenn.edu](mailto:sashafr@upenn.edu)

![alt text](http://www.library.upenn.edu/images/staff/laallen125.jpg "Laurie Allen")

Laurie Allen, Assistant Director for Digital Scholarship

215-746-2662 | @laallen

[laallen@upenn.edu](mailto:laallen@upenn.edu)

Katia Strieck, Head of Metadata Services

215-746-6396

[kstrieck@pobox.upenn.edu](mailto:kstrieck@pobox.upenn.edu)

![alt text](http://www.library.upenn.edu/images/staff/pguar125.jpg "Patricia Guardiola")

Patricia Guardiola, Assistant Head of the Fine Arts Library

215-573-4637

[pguar@upenn.edu](mailto:pguar@upenn.edu)

![alt text](https://www.sas.upenn.edu/anthropology/sites/www.sas.upenn.edu.anthropology/files/imagecache/bio-picture/website.jpg "Shannon Renninger")

Shannon Renninger, Undergraduate Coordinator, Department of Anthropology

215-746-0418 | (cell) 724-984-1586 | @shannonrenn

[srennin@sas.upenn.edu](mailto:srennin@sas.upenn.edu)

![alt text](https://iweb.museum.upenn.edu/images/staff/Archives-Pezzati-Alex.JPG "Alex Pezzati")

Alex Pezzati, Senior Archivist

215-898-8304

[apezzati@upenn.edu](mailto:apezzati@upenn.edu)

![alt text](https://iweb.museum.upenn.edu/images/staff/Archives-Pourshariati-Kate.jpg "Kate Pourshariati")

Kate Pourshariati, Film Archivist

215-898-8304

[katepour@upenn.edu](mailto:katepour@upenn.edu)

![alt text](https://iweb.museum.upenn.edu/images/staff/American-Wierzbowski-Bill.JPG "Bill Wierzbowski")

Bill Wierzbowski, American Section Keeper

215-898-0936

[wierzbow@upenn.edu](mailto:wierzbow@upenn.edu)
